name: 🐛 Bug Report
description: Report a bug or crash in a specific app.
title: "[bug]: "
labels: ["bug"]
body:
  - type: dropdown
    id: app_name
    attributes:
      label: App Name
      description: Which app is experiencing the issue?
      options:
        - pdf
        - openassistant
        - crypto
        - chess
        - calendar
        - contacts
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: App Version
      description: What version of the app are you running? (e.g., v1.0.2)
      placeholder: vX.X.X
    validations:
      required: true
  - type: textarea
    id: bug_description
    attributes:
      label: What is the bug?
      description: A clear and concise description of the issue.
    validations:
      required: true
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: What specific steps cause the bug to happen?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Log Files
      description: If the app crashed, please paste the log files here.
      render: shell