name: ✨ Feature Request
description: Suggest a new idea for a specific app.
title: "[feat]: "
labels: ["enhancement"]
body:
  - type: dropdown
    id: app_name
    attributes:
      label: App Name
      description: Which app is this feature for?
      options:
        - pdf
        - openassistant
        - crypto
        - chess
        - calendar
        - contacts
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: What feature should be added and why is it important?
      placeholder: Describe the "what" and the "why" here.
    validations:
      required: true