package com.vayunmathur.calendar.util

import android.content.Context
import android.util.Log
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json

@Serializable
data class HolidayCountry(val code: String, val name: String)

@Serializable
data class HolidayEntry(val d: String, val n: String)

/**
 * Reads the offline holiday data bundled under `assets/holidays/`
 * (`index.json` = country list, `<CODE>.json` = that country's holidays).
 * Generated by the host-only `:tools:holidaygen` module — no network needed.
 */
object HolidayData {
    private val json = Json { ignoreUnknownKeys = true }
    @Volatile private var countriesCache: List<HolidayCountry>? = null

    fun countries(context: Context): List<HolidayCountry> {
        countriesCache?.let { return it }
        val loaded = runCatching {
            val text = context.assets.open("holidays/index.json").bufferedReader().use { it.readText() }
            json.decodeFromString<List<HolidayCountry>>(text)
        }.onFailure { Log.e("HolidayData", "Failed reading index.json", it) }
            .getOrDefault(emptyList())
        countriesCache = loaded
        return loaded
    }

    fun holidays(context: Context, code: String): List<HolidayEntry> =
        runCatching {
            val text = context.assets.open("holidays/$code.json").bufferedReader().use { it.readText() }
            json.decodeFromString<List<HolidayEntry>>(text)
        }.onFailure { Log.e("HolidayData", "Failed reading $code.json", it) }
            .getOrDefault(emptyList())
}
